### ISSUE TITLE
 Question about the code of the class GaborLayerLearnable(nn.Module)

### ISSUE THREAD

**Issue by happyday521** [BCV-Uniandes/Gabor_Layers_for_Robustness#1]
Hi, great work! I have a question about the code of the class GaborLayerLearnable(nn.Module). In the following code, 
why did you set the self.gabor_kernels'  requires_grad=False? Thanks!
![image](https://user-images.githubusercontent.com/35884085/116197577-803ec700-a767-11eb-9f8e-8f369b7d8a82.png)

**Comment by juancprzs** [comment]
Hi there,

Thank you for your interest in our work!

I believe you are asking for [this line of code](https://github.com/BCV-Uniandes/Gabor_Layers_for_Robustness/blob/master/models/gabor_layers.py#L207). This part of the implementation is for the class `GaborLayerLearnable` instead of `GaborLayer`. The `GaborLayerLearnable` class was an experimental class on which we ran preliminary experiments, and is **not** the implementation whose results we report in the paper. 

The intent of this class was to learn the orientations (the _theta_ parameter of the Gabor function) along with all the other parameters. Our experiments with this class did not work sufficiently well, and so we stopped experimenting with it. The code you see regarding these experiments is rather a "vestige", and so it may, unfortunately, now contain some errors. These errors, however, do not affect the reported results.

Please let us know if there is anything else we can help with!

**Comment by happyday521** [comment]
Got it！Thanks for your quick reply！
